using System;
using System.Collections.Generic;
using Lexy.Compiler.Compiler.CSharp.FunctionCalls;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace Lexy.Compiler.Compiler.CSharp.ExpressionStatements;

//A lexy function is called without assignment (at statement level) which means it should auto map it's results and parameters
//Otherwise LexyFunctionCallExpression's syntax is generated by LexyFunctionCall
//LexyFunction()
internal static class AutoMapLexyFunctionStatement
{
    public static bool Matches(Language.Expressions.Functions.LexyFunctionCallExpression expression)
    {
        if (!expression.AutoMap)
        {
            throw new InvalidOperationException("AutoMap should be set to true for a statement.");
        }
        return true;
    }

    public static IEnumerable<StatementSyntax> Create(Language.Expressions.Functions.LexyFunctionCallExpression expression)
    {
        if (expression == null) throw new ArgumentNullException(nameof(expression));

        var parameterVariable = $"{LexyCodeConstants.ParameterVariable}_{expression.Reference.LineNumber}";
        var resultsVariable = $"{LexyCodeConstants.ResultsVariable}_{expression.Reference.LineNumber}";

        var result = new List<StatementSyntax>();

        result.AddRange(FillFunctionStatement.FillStatementSyntax(
            parameterVariable,
            expression.FunctionParametersTypes,
            expression.MappingParameters));

        result.Add(RunFunction(expression, parameterVariable, resultsVariable));

        result.AddRange(ExtractFunctionStatement.ExtractStatementSyntax(
            expression.MappingResults,
            resultsVariable));

        return result;
    }

    private static StatementSyntax RunFunction(Language.Expressions.Functions.LexyFunctionCallExpression lexyFunctionCallExpression, string parameterVariable,
        string resultsVariable)
    {
        var initialize = LexyFunctionCallSyntax.RunFunction(lexyFunctionCallExpression.FunctionName, parameterVariable);

        var variable = VariableDeclarator(Identifier(resultsVariable))
            .WithInitializer(EqualsValueClause(initialize));

        return LocalDeclarationStatement(
            VariableDeclaration(Types.Syntax(lexyFunctionCallExpression.FunctionResultsType))
                .WithVariables(SingletonSeparatedList(variable)));
    }
}